=== sarabjit20s/saaj-ui/apps/www/public/schema/registry-item.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the item. This is used to identify the item in the registry. It should be unique for your registry."
    },
    "type": {
      "type": "string",
      "enum": [
        "registry:ui",
        "registry:component",
        "registry:hook",
        "registry:util",
        "registry:block",
        "registry:file"
      ],
      "description": "The type of the item. This is used to determine the type and target path of the item when resolved for a project."
    },
    "description": {
      "type": "string",
      "description": "The description of the item. This is used to provide a brief overview of the item."
    },
    "title": {
      "type": "string",
      "description": "The human-readable title for your registry item. Keep it short and descriptive."
    },
    "author": {
      "type": "string",
      "description": "The author of the item. Recommended format: username <url>"
    },
    "dependencies": {
      "type": "array",
      "description": "An array of NPM dependencies required by the registry item.",
      "items": {
        "type": "string"
      }
    },
    "devDependencies": {
      "type": "array",
      "description": "An array of NPM dev dependencies required by the registry item.",
      "items": {
        "type": "string"
      }
    },
    "registryDependencies": {
      "type": "array",
      "description": "An array of registry items that this item depends on.",
      "items": {
        "type": "string"
      }
    },
    "files": {
      "type": "array",
      "description": "The main payload of the registry item. This is an array of files that are part of the registry item. Each file is an object with a path, content, type, and target.",
      "items": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "The path to the file relative to the registry root."
          },
          "content": {
            "type": "string",
            "description": "The content of the file."
          },
          "type": {
            "type": "string",
            "enum": [
              "registry:util",
              "registry:block",
              "registry:component",
              "registry:ui",
              "registry:hook",
              "registry:theme",
              "registry:page",
              "registry:file",
              "registry:style",
              "registry:base",
              "registry:item"
            ],
            "description": "The type of the file. This is used to determine the type of the file when resolved for a project."
          },
          "target": {
            "type": "string",
            "description": "The target path of the file. This is the path to the file in the project."
          }
        },
        "if": {
          "properties": {
            "type": {
              "enum": ["registry:file"]
            }
          }
        },
        "then": {
          "required": ["path", "type", "target"]
        },
        "else": {
          "required": ["path", "type"]
        }
      }
    },
    "meta": {
      "type": "object",
      "description": "Additional metadata for the registry item. This is an object with any key value pairs.",
      "additionalProperties": true
    },
    "docs": {
      "type": "string",
      "description": "The documentation for the registry item. This is a markdown string."
    }
  }
}

=== sarabjit20s/saaj-ui/apps/www/public/r/badge.json
{
  "$schema": "https://saaj-ui.vercel.app/schema/registry-item.json",
  "name": "badge",
  "type": "registry:ui",
  "registryDependencies": [
    "icon",
    "text"
  ],
  "files": [
    {
      "path": "src/registry/ui/badge.tsx",
      "content": "import React, { createContext, useContext, useMemo } from 'react';\nimport { View } from 'react-native';\nimport { StyleSheet } from 'react-native-unistyles';\n\nimport { Icon, IconProps } from '@/registry/ui/icon';\nimport { Text, TextProps } from '@/registry/ui/text';\nimport { Color } from '@/styles/tokens/colors';\n\ntype BadgeVariant =\n  | 'primary'\n  | 'secondary'\n  | 'destructive'\n  | 'success'\n  | 'outline';\n\ntype BadgeContextType = {\n  variant: BadgeVariant;\n};\n\nconst BadgeContext = createContext<BadgeContextType | null>(null);\n\nconst useBadge = () => {\n  const ctx = useContext(BadgeContext);\n  if (!ctx) {\n    throw new Error('useBadge must be used within a <Badge />');\n  }\n  return ctx;\n};\n\ntype BadgeProps = React.ComponentPropsWithRef<typeof View> & {\n  variant?: BadgeVariant;\n  iconOnly?: boolean;\n};\n\nfunction Badge({\n  variant = 'primary',\n  iconOnly = false,\n  style,\n  ...restProps\n}: BadgeProps) {\n  styles.useVariants({\n    variant,\n  });\n\n  const contextValue = useMemo<BadgeContextType>(() => {\n    return {\n      variant,\n    };\n  }, [variant]);\n\n  return (\n    <BadgeContext value={contextValue}>\n      <View\n        style={[styles.badge, iconOnly && styles.badgeIconOnly, style]}\n        {...restProps}\n      />\n    </BadgeContext>\n  );\n}\n\nconst fgColorMap: Record<NonNullable<BadgeProps['variant']>, Color> = {\n  primary: 'primaryForeground',\n  secondary: 'secondaryForeground',\n  destructive: 'destructiveForeground',\n  success: 'successForeground',\n  outline: 'secondaryForeground',\n};\n\nfunction BadgeText(props: TextProps) {\n  const { variant } = useBadge();\n\n  return <Text color={fgColorMap[variant]} variant=\"labelXs\" {...props} />;\n}\n\nBadge.Text = BadgeText;\n\nfunction BadgeIcon(props: IconProps) {\n  const { variant } = useBadge();\n\n  return <Icon color={fgColorMap[variant]} size={14} {...props} />;\n}\n\nBadge.Icon = BadgeIcon;\n\nconst styles = StyleSheet.create(({ colors, radius, space }) => ({\n  badge: {\n    flexDirection: 'row',\n    alignItems: 'center',\n    justifyContent: 'center',\n    borderRadius: radius.full,\n    borderCurve: 'continuous',\n    gap: space.xs,\n    paddingVertical: space.xs,\n    paddingHorizontal: space.md,\n    variants: {\n      variant: {\n        primary: {\n          backgroundColor: colors.primary,\n        },\n        secondary: {\n          backgroundColor: colors.secondary,\n        },\n        destructive: {\n          backgroundColor: colors.destructive,\n        },\n        success: {\n          backgroundColor: colors.success,\n        },\n        outline: {\n          borderWidth: 1,\n          borderColor: colors.border,\n        },\n      },\n    },\n  },\n  badgeIconOnly: {\n    paddingHorizontal: space.xs,\n  },\n}));\n\nexport { Badge, useBadge };\nexport type { BadgeProps };\n",
      "type": "registry:ui"
    }
  ]
}

=== sarabjit20s/saaj-ui/apps/www/public/r/spinner.json
{
  "$schema": "https://saaj-ui.vercel.app/schema/registry-item.json",
  "name": "spinner",
  "type": "registry:ui",
  "dependencies": [
    "react-native-svg"
  ],
  "registryDependencies": [
    "icon"
  ],
  "files": [
    {
      "path": "src/registry/ui/spinner.tsx",
      "content": "import { useEffect } from 'react';\nimport Animated, {\n  useSharedValue,\n  useAnimatedStyle,\n  withRepeat,\n  withTiming,\n  Easing,\n} from 'react-native-reanimated';\nimport Svg, { Defs, LinearGradient, Path, Stop } from 'react-native-svg';\nimport { useUnistyles } from 'react-native-unistyles';\n\nimport { Color } from '@/styles/tokens/colors';\n\ntype SpinnerProps = {\n  size?: number;\n  color?: Color;\n  /**\n   * Whether the spinner is loading or not\n   */\n  loading?: boolean;\n  /**\n   * Speed of the spinner in milliseconds\n   */\n  speed?: number;\n};\n\nfunction Spinner({ loading = true, ...props }: SpinnerProps) {\n  if (!loading) {\n    return null;\n  }\n  return <SpinnerImpl loading={loading} {...props} />;\n}\n\nfunction SpinnerImpl({\n  size = 24,\n  color: colorProp = 'foreground',\n  speed = 800,\n}: SpinnerProps) {\n  const { theme } = useUnistyles();\n\n  const color = theme.colors[colorProp];\n\n  const rotation = useSharedValue(0);\n\n  useEffect(() => {\n    rotation.value = withRepeat(\n      withTiming(360, { duration: speed, easing: Easing.linear }),\n      -1,\n      false,\n    );\n    // eslint-disable-next-line react-hooks/exhaustive-deps\n  }, [speed]);\n\n  const animatedStyle = useAnimatedStyle(() => ({\n    transform: [{ rotate: `${rotation.value}deg` }],\n  }));\n\n  return (\n    <Animated.View style={[{ width: size, height: size }, animatedStyle]}>\n      <Svg width={size} height={size} viewBox=\"0 0 24 24\">\n        <Defs>\n          <LinearGradient\n            id=\"gradient\"\n            x1=\"75%\"\n            x2=\"50%\"\n            y1=\"0%\"\n            y2=\"100%\"\n            gradientTransform=\"rotate(-100)\"\n          >\n            <Stop offset=\"0%\" stopColor={color} />\n            <Stop offset=\"100%\" stopColor={color} stopOpacity={0} />\n          </LinearGradient>\n        </Defs>\n\n        <Path\n          d=\"M10.25 1.55a1.5 1.5 0 1 1 .497 2.958A7.5 7.5 0 1 0 18 12a1.5 1.5 0 0 1 3 0c0 5.799-4.701 10.5-10.5 10.5S0 17.799 0 12C0 6.855 3.726 2.49 8.749 1.646\"\n          fill=\"url(#gradient)\"\n          transform=\"translate(1.5 0)\"\n        />\n      </Svg>\n    </Animated.View>\n  );\n}\n\nexport { Spinner };\nexport type { SpinnerProps };\n",
      "type": "registry:ui"
    }
  ]
}

=== sarabjit20s/saaj-ui/apps/www/public/r/checkbox.json
{
  "$schema": "https://saaj-ui.vercel.app/schema/registry-item.json",
  "name": "checkbox",
  "type": "registry:ui",
  "dependencies": [
    "react-native-svg"
  ],
  "registryDependencies": [
    "icon",
    "use-controllable-state"
  ],
  "files": [
    {
      "path": "src/registry/ui/checkbox.tsx",
      "content": "import React, { createContext, useCallback, useContext, useMemo } from 'react';\nimport {\n  GestureResponderEvent,\n  Insets,\n  Pressable,\n  PressableStateCallbackType,\n  StyleProp,\n  ViewStyle,\n} from 'react-native';\nimport { StyleSheet } from 'react-native-unistyles';\nimport { useAnimatedTheme } from 'react-native-unistyles/reanimated';\nimport Animated, {\n  interpolateColor,\n  SharedValue,\n  useAnimatedProps,\n  useAnimatedStyle,\n  useSharedValue,\n  withTiming,\n} from 'react-native-reanimated';\nimport Svg, { Path } from 'react-native-svg';\n\nimport { useControllableState } from '@/registry/hooks/use-controllable-state';\n\ntype CheckboxContextType = {\n  checked: boolean;\n  disabled: boolean;\n  progress: SharedValue<number>;\n};\n\nconst CheckboxContext = createContext<CheckboxContextType | null>(null);\n\nconst useCheckbox = () => {\n  const ctx = useContext(CheckboxContext);\n  if (!ctx) {\n    throw new Error('useCheckbox must be used within a <Checkbox />');\n  }\n  return ctx;\n};\n\nconst DEFAULT_HIT_SLOP: Insets = {\n  top: 8,\n  left: 8,\n  bottom: 8,\n  right: 8,\n};\n\ntype CheckboxProps = Omit<\n  React.ComponentPropsWithRef<typeof Pressable>,\n  'style'\n> & {\n  style?:\n    | StyleProp<ViewStyle>\n    | ((\n        state: PressableStateCallbackType,\n        context: CheckboxContextType,\n      ) => StyleProp<ViewStyle>);\n  checked?: boolean;\n  defaultChecked?: boolean;\n  onCheckedChange?: (checked: boolean) => void;\n};\n\nfunction Checkbox({\n  accessibilityState,\n  children,\n  defaultChecked,\n  checked: checkedProp,\n  onCheckedChange,\n  disabled = false,\n  onPress: onPressProp,\n  style,\n  ...restProps\n}: CheckboxProps) {\n  const [checked, setChecked] = useControllableState({\n    defaultValue: defaultChecked ?? false,\n    controlledValue: checkedProp,\n    onControlledChange: onCheckedChange,\n  });\n\n  const progress = useSharedValue(checked ? 1 : 0);\n\n  const onPress = useCallback(\n    (e: GestureResponderEvent) => {\n      const newValue = !checked;\n      setChecked(newValue);\n      progress.value = withTiming(newValue ? 1 : 0, { duration: 250 });\n      onPressProp?.(e);\n    },\n    [onPressProp, checked, setChecked, progress],\n  );\n\n  const contextValue = useMemo<CheckboxContextType>(() => {\n    return {\n      checked,\n      disabled: !!disabled,\n      progress,\n    };\n  }, [checked, disabled, progress]);\n\n  return (\n    <CheckboxContext value={contextValue}>\n      <Pressable\n        accessibilityRole=\"checkbox\"\n        accessibilityState={{\n          ...accessibilityState,\n          checked,\n          disabled: !!disabled,\n        }}\n        disabled={disabled}\n        onPress={onPress}\n        style={state => [\n          styles.checkbox,\n          typeof style === 'function' ? style(state, contextValue) : style,\n        ]}\n        {...restProps}\n      >\n        {children ?? <CheckboxIndicator />}\n      </Pressable>\n    </CheckboxContext>\n  );\n}\n\ntype CheckboxStateProps = {\n  children?: React.ReactNode | ((ctx: CheckboxContextType) => React.ReactNode);\n};\n\nfunction CheckboxState({ children }: CheckboxStateProps) {\n  const ctx = useCheckbox();\n  if (typeof children === 'function') {\n    return children(ctx);\n  }\n  return children;\n}\n\nCheckbox.State = CheckboxState;\n\ntype CheckboxIndicatorProps = {\n  children?: React.ReactNode;\n};\n\nfunction CheckboxIndicator({ children }: CheckboxIndicatorProps) {\n  const { disabled, progress } = useCheckbox();\n  const animatedTheme = useAnimatedTheme();\n\n  const animatedStyle = useAnimatedStyle(() => ({\n    opacity: disabled ? 0.5 : 1,\n    backgroundColor: interpolateColor(\n      progress.value,\n      [0, 1],\n      ['transparent', animatedTheme.value.colors.primary],\n    ),\n    borderColor: interpolateColor(\n      progress.value,\n      [0, 1],\n      [animatedTheme.value.colors.border, animatedTheme.value.colors.primary],\n    ),\n  }));\n\n  return (\n    <Animated.View\n      hitSlop={DEFAULT_HIT_SLOP}\n      style={[styles.indicator, animatedStyle]}\n    >\n      {children ?? <CheckboxIcon />}\n    </Animated.View>\n  );\n}\n\nCheckbox.Indicator = CheckboxIndicator;\n\nconst AnimatedPath = Animated.createAnimatedComponent(Path);\n\nconst CHECKMARK_PATH = 'M6 12L10 16L18 8';\nconst PATH_LENGTH = 20;\n\ntype CheckboxIconProps = {\n  size?: number;\n};\n\nfunction CheckboxIcon({ size = 22 }: CheckboxIconProps) {\n  const { progress } = useCheckbox();\n  const animatedPathProps = useAnimatedProps(() => ({\n    strokeDashoffset: PATH_LENGTH * (1 - progress.value),\n  }));\n\n  return (\n    <Svg width={size} height={size} viewBox=\"0 0 24 24\" fill=\"none\">\n      <AnimatedPath\n        d={CHECKMARK_PATH}\n        stroke=\"white\"\n        strokeWidth=\"2.25\"\n        strokeLinecap=\"round\"\n        strokeLinejoin=\"round\"\n        strokeDasharray={PATH_LENGTH}\n        animatedProps={animatedPathProps}\n      />\n    </Svg>\n  );\n}\n\nCheckbox.Icon = CheckboxIcon;\n\nconst styles = StyleSheet.create(({ radius, space }) => ({\n  checkbox: {\n    flexDirection: 'row',\n    alignItems: 'center',\n    gap: space.lg,\n  },\n  indicator: {\n    justifyContent: 'center',\n    alignItems: 'center',\n    width: 22,\n    height: 22,\n    borderWidth: 1.5,\n    borderRadius: radius.xs,\n    borderCurve: 'continuous',\n  },\n}));\n\nexport { Checkbox, useCheckbox };\nexport type { CheckboxProps };\n",
      "type": "registry:ui"
    }
  ]
}

=== sarabjit20s/saaj-ui/apps/www/public/r/dialog.json
{
  "$schema": "https://saaj-ui.vercel.app/schema/registry-item.json",
  "name": "dialog",
  "type": "registry:ui",
  "registryDependencies": [
    "text",
    "use-controllable-state",
    "compose-refs"
  ],
  "files": [
    {
      "path": "src/registry/ui/dialog.tsx",
      "content": "import React, {\n  createContext,\n  useCallback,\n  useContext,\n  useId,\n  useMemo,\n  useRef,\n} from 'react';\nimport {\n  GestureResponderEvent,\n  Modal,\n  Pressable,\n  PressableProps,\n  View,\n} from 'react-native';\nimport { StyleSheet } from 'react-native-unistyles';\nimport Animated, {\n  Easing,\n  FadeIn,\n  FadeOut,\n  Keyframe,\n} from 'react-native-reanimated';\nimport { KeyboardAvoidingView } from 'react-native-keyboard-controller';\n\nimport { Text, TextProps } from '@/registry/ui/text';\nimport { useControllableState } from '@/registry/hooks/use-controllable-state';\nimport { useComposedRefs } from '@/registry/utils/compose-refs';\n\ntype DialogContextType = {\n  defaultOpen: boolean;\n  open: boolean;\n  onOpen: () => void;\n  onClose: () => void;\n  closeOnOutsidePress: boolean;\n  closeOnBackPress: boolean;\n  triggerRef: React.RefObject<View | null>;\n  titleId: string;\n};\n\nconst DialogContext = createContext<DialogContextType | null>(null);\n\nconst useDialog = () => {\n  const ctx = useContext(DialogContext);\n  if (!ctx) {\n    throw new Error('useDialog must be used within a <Dialog />');\n  }\n  return ctx;\n};\n\ntype DialogProps = {\n  children?: React.ReactNode;\n  defaultOpen?: boolean;\n  open?: boolean;\n  onOpenChange?: (open: boolean) => void;\n  /**\n   * Whether to close the dialog when pressing outside(on overlay) of it.\n   */\n  closeOnOutsidePress?: boolean;\n  /**\n   * Whether to close the dialog when pressing the back button on Android.\n   */\n  closeOnBackPress?: boolean;\n};\n\nfunction Dialog({\n  children,\n  defaultOpen = false,\n  open: openProp,\n  onOpenChange,\n  closeOnOutsidePress = true,\n  closeOnBackPress = true,\n}: DialogProps) {\n  const [open, setOpen] = useControllableState({\n    defaultValue: defaultOpen,\n    controlledValue: openProp,\n    onControlledChange: onOpenChange,\n  });\n\n  const triggerRef = useRef<View | null>(null);\n  const titleId = useId();\n\n  const onOpen = useCallback(() => {\n    setOpen(true);\n  }, [setOpen]);\n\n  const onClose = useCallback(() => {\n    setOpen(false);\n  }, [setOpen]);\n\n  const contextValue = useMemo<DialogContextType>(\n    () => ({\n      defaultOpen,\n      open,\n      onOpen,\n      onClose,\n      triggerRef,\n      titleId,\n      closeOnOutsidePress,\n      closeOnBackPress,\n    }),\n    [\n      closeOnBackPress,\n      closeOnOutsidePress,\n      defaultOpen,\n      onClose,\n      onOpen,\n      open,\n      titleId,\n    ],\n  );\n\n  return <DialogContext value={contextValue}>{children}</DialogContext>;\n}\n\ntype DialogTriggerProps<T extends React.ElementType = typeof Pressable> =\n  React.ComponentPropsWithoutRef<T> & {\n    as?: T;\n    ref?: React.Ref<View>;\n  };\n\nfunction DialogTrigger<T extends React.ElementType<PressableProps>>({\n  as,\n  ref,\n  accessibilityState,\n  disabled,\n  onPress: onPressProp,\n  ...restProps\n}: DialogTriggerProps<T>) {\n  const { open, onOpen, triggerRef } = useDialog();\n\n  const composedRefs = useComposedRefs(triggerRef, ref);\n\n  const onPress = React.useCallback(\n    (e: GestureResponderEvent) => {\n      onOpen();\n      onPressProp?.(e);\n    },\n    [onPressProp, onOpen],\n  );\n\n  const Comp = as ?? Pressable;\n\n  return (\n    <Comp\n      ref={composedRefs}\n      accessibilityRole=\"button\"\n      accessibilityState={{\n        ...accessibilityState,\n        expanded: open,\n        disabled: !!disabled,\n      }}\n      disabled={disabled}\n      onPress={onPress}\n      {...restProps}\n    />\n  );\n}\n\nDialog.Trigger = DialogTrigger;\n\nconst AnimatedPressable = Animated.createAnimatedComponent(Pressable);\n\nconst animConfig = {\n  duration: 250,\n  easing: Easing.inOut(Easing.ease),\n} as const;\n\nfunction DialogOverlay() {\n  const { onClose, closeOnOutsidePress } = useDialog();\n\n  return (\n    <AnimatedPressable\n      accessible={false}\n      accessibilityElementsHidden={true}\n      importantForAccessibility=\"no\"\n      disabled={!closeOnOutsidePress}\n      entering={FadeIn.duration(animConfig.duration).easing(animConfig.easing)}\n      exiting={FadeOut.duration(animConfig.duration).easing(animConfig.easing)}\n      onPress={onClose}\n      style={styles.overlay}\n    />\n  );\n}\n\nconst entryAnim = new Keyframe({\n  0: {\n    opacity: 0,\n    transform: [{ scale: 0.95 }],\n  },\n  100: {\n    opacity: 1,\n    transform: [{ scale: 1 }],\n    easing: animConfig.easing,\n  },\n});\n\nconst exitAnim = new Keyframe({\n  0: {\n    opacity: 1,\n    transform: [{ scale: 1 }],\n  },\n  100: {\n    opacity: 0,\n    transform: [{ scale: 0.95 }],\n    easing: animConfig.easing,\n  },\n});\n\ntype DialogContentProps = React.ComponentPropsWithRef<typeof View> & {\n  enableKeyboardAvoidingView?: boolean;\n};\n\nfunction DialogContent({\n  enableKeyboardAvoidingView = false,\n  style,\n  ...restProps\n}: DialogContentProps) {\n  const { open, closeOnBackPress, titleId, onClose } = useDialog();\n\n  const handleRequestClose = useCallback(() => {\n    if (closeOnBackPress) {\n      onClose();\n    }\n  }, [closeOnBackPress, onClose]);\n\n  if (!open) {\n    return;\n  }\n\n  return (\n    <Modal\n      visible={true}\n      transparent={true}\n      statusBarTranslucent={true}\n      navigationBarTranslucent={true}\n      animationType=\"none\"\n      accessibilityLabelledBy={titleId}\n      onRequestClose={handleRequestClose}\n    >\n      <DialogOverlay />\n      <View pointerEvents=\"box-none\" style={styles.contentContainer}>\n        <KeyboardAvoidingView\n          behavior=\"padding\"\n          keyboardVerticalOffset={24}\n          enabled={enableKeyboardAvoidingView}\n          style={styles.keyboardAvoidingView}\n        >\n          <Animated.View\n            entering={entryAnim.duration(animConfig.duration)}\n            exiting={exitAnim.duration(animConfig.duration)}\n            style={[styles.content, style]}\n            {...restProps}\n          />\n        </KeyboardAvoidingView>\n      </View>\n    </Modal>\n  );\n}\n\nDialog.Content = DialogContent;\n\nfunction DialogHeader({\n  style,\n  ...restProps\n}: React.ComponentPropsWithRef<typeof View>) {\n  return <View style={[styles.header, style]} {...restProps} />;\n}\n\nDialog.Header = DialogHeader;\n\nfunction DialogFooter({\n  style,\n  ...restProps\n}: React.ComponentPropsWithRef<typeof View>) {\n  return <View style={[styles.footer, style]} {...restProps} />;\n}\n\nDialog.Footer = DialogFooter;\n\nfunction DialogTitle(props: TextProps) {\n  const { titleId } = useDialog();\n\n  return <Text nativeID={titleId} variant=\"headlineXs\" {...props} />;\n}\n\nDialog.Title = DialogTitle;\n\nfunction DialogDescription(props: TextProps) {\n  return <Text color=\"mutedForeground\" variant=\"bodyMd\" {...props} />;\n}\n\nDialog.Description = DialogDescription;\n\ntype DialogCloseProps<T extends React.ElementType = typeof Pressable> =\n  React.ComponentPropsWithoutRef<T> & {\n    as?: T;\n    ref?: React.Ref<View>;\n  };\n\nfunction DialogClose<T extends React.ElementType<PressableProps>>({\n  as,\n  onPress: onPressProp,\n  ...restProps\n}: DialogCloseProps<T>) {\n  const { onClose } = useDialog();\n\n  const onPress = useCallback(\n    (e: GestureResponderEvent) => {\n      onClose();\n      onPressProp?.(e);\n    },\n    [onPressProp, onClose],\n  );\n\n  const Comp = as ?? Pressable;\n\n  return <Comp accessibilityRole=\"button\" onPress={onPress} {...restProps} />;\n}\n\nDialog.Close = DialogClose;\n\nconst styles = StyleSheet.create(({ colors, radius, space }, rt) => ({\n  container: {\n    flex: 1,\n    width: rt.screen.width,\n    height: rt.screen.height,\n  },\n  overlay: {\n    ...StyleSheet.absoluteFillObject,\n    backgroundColor: colors.overlay,\n  },\n  keyboardAvoidingView: {\n    width: '100%',\n  },\n  contentContainer: {\n    flex: 1,\n    width: '100%',\n    height: '100%',\n    alignItems: 'center',\n    justifyContent: 'center',\n    paddingHorizontal: space['3xl'],\n  },\n  content: {\n    maxHeight: rt.screen.height - rt.insets.top - rt.insets.bottom,\n    maxWidth: 480,\n    width: '100%',\n    gap: space.lg,\n    padding: space.xl,\n    borderRadius: radius['2xl'],\n    borderCurve: 'continuous',\n    backgroundColor: colors.dialog,\n    boxShadow: `0px 4px 24px 2px rgba(0, 0, 0, 0.1)`,\n  },\n  header: {\n    gap: space.md,\n    padding: space.md,\n  },\n  footer: {\n    flexDirection: 'row',\n    justifyContent: 'flex-end',\n    gap: space.lg,\n  },\n}));\n\nexport { Dialog, useDialog };\nexport type { DialogProps };\n",
      "type": "registry:ui"
    }
  ]
}
